@startuml
set namespaceSeparator ?
hide circle
hide class fields

package IG #DDDDDD{

     package Profiles #DDDDDD{

        class AsMailboxMSSProfile{

             ContactPoint => [None..None]
             ContactPoint.extension:emailType => <&plus>[None..None]
             ContactPoint.extension:emailType.value[x] => <&plus>[None..None]
             ContactPoint.system => [None..None]
             ContactPoint.value => [None..None]
        } 

        class AsOrganizationProfile{

             Organization => [None..None]
             Organization.telecom => [None..None]
             Organization.telecom:mailbox-mss => [0..*]
         }

     }
     package extension #paleturquoise {


         }
     }
     package valueset #PaleVioletRed{
       }

package "Ressources de base" #palegreen {

 class "https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-contact-point" as  classf60483b0623e1893e0fa6d23ce4ea871 

    classf60483b0623e1893e0fa6d23ce4ea871 --> AsMailboxMSSProfile

 class "https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-organization" as  class7273115ddeceb35c4c7044f07f832f67 

    class7273115ddeceb35c4c7044f07f832f67 --> AsOrganizationProfile
}
@enduml